alter table reservation drop constraint FK7lj6uw4q638hp6ltj2n0oa2l;
alter table reservation drop constraint FKrea93581tgkq61mdl13hehami;
alter table users_roles drop constraint FKj6m8fwv7oqv74fcehir1a9ffy;
alter table users_roles drop constraint FK2o0jvgh89lemvvo17cbqvdxaa;
drop table if exists faq cascade;
drop table if exists gift cascade;
drop table if exists itinerary cascade;
drop table if exists reservation cascade;
drop table if exists roles cascade;
drop table if exists users cascade;
drop table if exists users_roles cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table faq (faq_id int8 not null, a TEXT, last_updated timestamp, q varchar(255), primary key (faq_id));
create table gift (gift_id int8 not null, description TEXT, image varchar(255), link varchar(255), name varchar(255), percentage_reserved int4 not null, price float8, splitable boolean not null, visible boolean not null, primary key (gift_id));
create table itinerary (itinerary_id int8 not null, date_time timestamp, description TEXT, last_updated timestamp, location varchar(255), title varchar(255), primary key (itinerary_id));
create table reservation (reservation_id int8 not null, percentage int4, gift_id int8, user_id int8, primary key (reservation_id));
create table roles (role_id int8 not null, name varchar(255), primary key (role_id));
create table users (user_id int8 not null, email varchar(255), enabled boolean not null, name varchar(255) not null, password varchar(255) not null, verification_code varchar(64), primary key (user_id));
create table users_roles (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table reservation add constraint FK7lj6uw4q638hp6ltj2n0oa2l foreign key (gift_id) references gift;
alter table reservation add constraint FKrea93581tgkq61mdl13hehami foreign key (user_id) references users;
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles;
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;